### ISSUE TITLE
KeyError: 'A_0' on training.

### ISSUE THREAD

**Issue by toniesteves** [VSAnimator/stgan#1]
When I call 

`python test.py --dataroot ./path/to/data/combined  --name stgan --model temporal_branched_ir --netG unet_256_independent --input_nc 4`

I receive the following error:

Traceback (most recent call last):
  File "train.py", line 50, in <module>
    model.set_input(data)         # unpack data from dataset and apply preprocessing
  File "/home/toni/Git/stgan/models/temporal_branched_model.py", line 82, in set_input
    self.real_A_0 = input['A_0'].to(self.device)
KeyError: 'A_0'

-------

Ubuntu 16.04
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by VSAnimator** [comment]
Can you please clarify the correspondence between the command called and the traceback? The command called is on "test.py" with "temporal_branched_ir" model, whereas the traceback is for "train.py" with the "temporal_branched" model.

**Comment by toniesteves** [comment]
Sorry, it was a typo. Indeed the error shows up when I call:

`python train.py --dataroot combined/  --name stgan --model temporal_branched --netG unet_256_independent --input_nc 4`

before the error it prints the following report:

```
----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: combined/                     	[default: None]
             dataset_mode: aligned                       
                direction: AtoB                          
              display_env: main                          
             display_freq: 400                           
               display_id: 1                             
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: vanilla                       
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 4                             	[default: 3]
                  isTrain: True                          	[default: None]
                lambda_L1: 100.0                         
                load_iter: 0                             	[default: 0]
                load_size: 286                           
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: temporal_branched             	[default: cycle_gan]
               n_layers_D: 3                             
                     name: stgan                         	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256_independent          	[default: unet_256]
                      ngf: 64                            
                    niter: 100                           
              niter_decay: 100                           
               no_dropout: False                         
                  no_flip: False                         
                  no_html: False                         
                     norm: batch                         
              num_threads: 4                             
                output_nc: 3                             
                    phase: train                         
                pool_size: 0                             
               preprocess: resize_and_crop               
               print_freq: 100                           
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000                          
                 scramble: False                         
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------
dataset [AlignedDataset] was created
The number of training images = 78112
initialize network with normal
initialize network with normal
model [TemporalBranchedModel] was created
---------- Networks initialized -------------
[Network G] Total number of parameters : 93.481 M
[Network D] Total number of parameters : 2.778 M
-----------------------------------------------
```

am I missing something?
